import os

base = r'c:\Users\HP\Documents\antigravity\vibrant-kepler\obsidian_vault\raw_research\snippets'
os.makedirs(base, exist_ok=True)

files = {
'logit_bias.md': """# Logit Bias in Constrained Generation\n\n## Mechanism\nLogit bias modifies token generation probabilities at inference time prior to softmax. For logit vector z, an additive scalar bias b_i is injected for target token i:\nP(w_i) = exp(z_i + b_i) / sum_j exp(z_j + b_j)\n\n- **Suppression (b_i << 0):** Setting -100 drives probability to 0, banning the token.\n- **Forcing (b_i >> 0):** Setting +100 virtually guarantees token emission.\n- **Calibration:** Moderate values [-5, +5] guide style without strict forcing.\n\n## Use Cases\n1. **Categorical Constraints:** Restrict output to \"Yes\"/\"No\" or MCQ options A/B/C/D.\n2. **Grammar Enforcement:** Outlines/Guidance apply dynamic state-dependent logit masks at each step.\n3. **Safety Guardrails:** Ban toxic strings, PII, or premature refusal prefixes.\n4. **Flow Control:** Force/suppress special tokens (tool-call delimiters, EOS markers).""",

'automatic_prompt_engineer.md': """# Automatic Prompt Engineer (APE) - Zhou et al. (ICLR 2023)\n\n**Citation:** arXiv:2211.01910 - *Large Language Models Are Human-Level Prompt Engineers*\n\n## Core Paradigm\nFrames prompt design as black-box optimization: max_p E[(x,y)][f(p,x,y)]\n\n## Mechanism\n1. **Candidate Generation:** LLM conditioned on input-output demos to propose candidate instructions (forward generation, reverse generation, meta-prompting).\n2. **Scoring:** Execution accuracy or likelihood scoring: sum log P(y|p,x).\n3. **Refinement:** Generates semantic variants around top-performing candidates.\n\n## Key Findings\n- Outperformed human heuristics on 19/24 Instruction Induction tasks.\n- Discovered zero-shot CoT trigger: *\"Let's work this out step by step to be sure we have the right answer.\"*\n- Surpassed Kojima et al.'s \"Let's think step by step\" on MultiArith (82.0% vs. 78.7%).""",

'self_rag.md': """# Self-RAG: Self-Reflective Retrieval-Augmented Generation (Asai et al., 2023)\n\n## Reflection Tokens\n1. **[Retrieve] / [No Retrieve]:** Model learns when retrieval is actually needed.\n2. **[IsREL]:** Is retrieved passage relevant?\n3. **[IsSUP]:** Is generation grounded/supported by evidence?\n4. **[IsUSE]:** Is the answer useful?\n\n## Training Pipeline\n- **Critic Model:** Trained on GPT-4-annotated corpus to insert reflection tokens.\n- **Generator:** Fine-tuned to jointly predict text tokens and reflection tokens in one autoregressive pass.\n\n## Inference\n- Segment-level beam search across multiple retrieved passages.\n- Reflection token probabilities score branches.\n- Test-time controllability: tune thresholds without retraining.""",

'contrastive_cot.md': """# Contrastive Chain-of-Thought (CCoT) - Chia et al. (2023)\n\n**Citation:** arXiv:2311.09277\n\n## Core Concept\nPairs valid AND invalid reasoning demonstrations to teach models to avoid logical pitfalls.\n\n## Prompt Structure\n- Question: Target reasoning problem\n- Explanation (INCORRECT): Plausible but flawed logic to avoid\n- Explanation (CORRECT): Valid step-by-step reasoning\n- Answer: Ground truth\n\n## Negative Generation Methods\n1. **Targeted perturbation:** Mutate numbers, operations, or entities in valid chains.\n2. **Model sampling:** Filter model rollouts for incorrect reasoning paths.\n\n## Results\n- **+4-13%** over standard CoT on arithmetic (GSM8K, SVAMP) and commonsense (StrategyQA, CSQA).\n- Synergistic with self-consistency.""",

'role_prompting.md': """# Role Prompting: Expert Personas\n\n## Mechanism\nConditions LLM with expert persona (e.g., \"You are an expert bioinformatician\"). Steers generation toward stylistic/lexical subspaces from training but does NOT inject new parametric knowledge.\n\n## Empirical Gains\n- **Reasoning Trigger:** Kong et al. (NAACL 2024): AQuA 53.5% → 63.8%; Last Letter 23.8% → 84.2%.\n- **Stylistic Alignment:** Significantly improves tone, domain terminology, audience adaptation.\n- **Rule-Based Personas:** Integrating operational guidelines improves multi-turn agent consistency.\n\n## Empirical Limits\n- **Knowledge Benchmarks:** Generic personas (\"world-class physicist\") yield negligible MMLU/GSM8K gains.\n- **Hallucination Risk:** Models optimize for persona conviction over truthfulness.\n- **Reasoning Interference:** Mismatched personas can reduce task performance by ~26%.\n- **Best Practice:** Pair with explicit constraints and few-shot/RAG exemplars.""",

'complexity_cot.md': """# Complexity-Based CoT (Fu et al., ICLR 2023)\n\n**Citation:** arXiv:2210.00720\n\n## Core Hypothesis\nDemonstrating higher reasoning complexity in few-shot exemplars elicits longer, more thorough reasoning chains.\n\n## Mechanisms\n1. **Complexity Metric:** Step count (newline splits) or total chain length.\n2. **Prompt Selection:** Automatically select exemplars with most reasoning steps.\n3. **Complexity-Based Consistency:** Restrict majority voting to top-K most complex sampled paths.\n\n## Results\n- Average **+5.3%** accuracy gain across multi-step benchmarks.\n- Up to **+18%** on challenging subsets.\n- Outperforms standard CoT on GSM8K, MathQA, MultiArith, BIG-Bench Hard.""",

'self_refine.md': """# Self-Refine (Madaan et al., NeurIPS 2023)\n\n**Citation:** arXiv:2303.17651\n\n## Architecture\nClosed loop with three modular roles, all executed by the SAME LLM:\n1. **Generate:** Initial candidate output from input prompt.\n2. **Feedback:** Multi-aspect natural language critique (code efficiency, readability, logic).\n3. **Refine:** Rewrite conditioned on prompt + previous draft + feedback.\nRepeats for max k iterations (typically k=2-4).\n\n## Results\n- Evaluated on 7 tasks: dialogue, code optimization, code readability, constrained gen, sentiment reversal, GSM8K, explanations.\n- ~20% absolute improvement across tasks.\n- No external verifier needed.\n\n## Limitations\n- Self-feedback can hallucinate non-existent issues.\n- Quality plateaus or degrades after 2-3 rounds.""",

'generated_knowledge.md': """# Generated Knowledge Prompting (Liu et al., ACL 2022)\n\n**Citation:** arXiv:2110.08387\n\n## Two-Stage Architecture\n1. **Knowledge Generation (M_gen):** LLM generates K discrete knowledge statements from query x using few-shot demos.\n2. **Knowledge Integration (M_eval):** Each statement k_i prepended to question, predictions aggregated via majority vote or probability-weighted ensemble.\n\n## Key Properties\n- No external retrieval corpus needed; uses parametric memory.\n- M_gen and M_eval can be different model sizes.\n- Low-quality knowledge degrades reasoning (\"Knowledge Poisoning\").\n\n## Performance\n- SOTA on CommonsenseQA, CommonsenseQA 2.0, NumerSense, QASC.\n- +4-10% over standard few-shot baselines.\n\n## Significance\nArchitectural bridge between RAG (external retrieval) and CoT (internal deduction).""",

'pal.md': """# Program-Aided Language Models (PAL) - Gao et al. (ICML 2023)\n\n**Citation:** arXiv:2211.10435\n\n## Core Concept\nDecouples reasoning from computation:\n- **Reasoning (LLM):** Translates problem into Python code with natural language comments.\n- **Computation (Interpreter):** Deterministic Python runtime executes the code.\n\n## Mechanism\n1. Few-shot exemplars show Python code as intermediate reasoning steps.\n2. Generated code executed in Python runtime.\n3. Runtime variables preserve intermediate states without hallucination.\n\n## Results\n- SOTA on GSM8K using Codex, surpassing PaLM-540B.\n- Tested across 13 tasks: math, symbolic, algorithmic reasoning.\n- Code generation pretraining generalizes to non-coding reasoning tasks.""",

'active_prompting.md': """# Active Prompting (Diao et al., ACL 2024)\n\n**Citation:** arXiv:2302.12246\n\n## Core Concept\nApplies active learning to select which questions to annotate with CoT rationales, targeting highest-uncertainty examples.\n\n## Four-Stage Pipeline\n1. **Uncertainty Estimation:** Query LLM k times per question with temperature > 0.\n2. **Metric Quantification:** Measure disagreement (distinct answers ratio) or entropy of prediction distributions.\n3. **Selective Annotation:** Human annotators write CoT rationales for top-N most uncertain questions.\n4. **Inference:** Annotated high-uncertainty exemplars used as few-shot prompt.\n\n## Results\n- Outperforms standard CoT, random selection, and self-consistency on GSM8K, SVAMP, ASDiv, StrategyQA.\n- Uncertainty strongly correlates with model error, ensuring exemplars cover boundary conditions.""",

'algorithm_of_thoughts.md': """# Algorithm of Thoughts (AoT) - Sel et al. (ICML 2024)\n\n**Citation:** arXiv:2308.10379\n\n## Core Motivation\nToT achieves deliberate search but requires 100+ API calls. AoT internalizes algorithmic search into a single LLM context window.\n\n## Mechanism\n- **In-Context Search Exemplars:** Few-shot demos show DFS/BFS: propose candidates, evaluate states, prune branches, backtrack.\n- **Hybrid Intuition-Search:** LLM fuses semantic prior with search heuristics, pruning suboptimal subtrees early.\n- **Single-Context:** Transformer's working memory maintains state across exploration steps.\n\n## Results (vs. ToT on Game of 24)\n- Matches ToT performance.\n- Reduces query count by 1-2 orders of magnitude (100+ → 1-2 queries).\n- Also tested on Mini Crosswords and TSP.""",

'lost_in_middle.md': """# Lost in the Middle (Liu et al., TACL 2024)\n\n**Citation:** arXiv:2307.03172\n\n## Core Finding: U-Shaped Performance Curve\nLLMs access information best at context boundaries:\n- **Primacy bias:** Information at the start of context.\n- **Recency bias:** Information at the end of context.\n- **Middle degradation:** Performance near closed-book baselines for middle-positioned evidence.\n\n## Scope\nAffects GPT-3.5/4, Claude, MPT-30B, LLaMA-2 — even models marketed for long context.\n\n## Mechanics\nCausal masking and positional encodings bias attention toward initial (structural anchors) and terminal (generation prefix) tokens.\n\n## Implications for RAG\n1. **Perimeter Reordering:** Top chunks at start/end; lowest-ranked in the center trough.\n2. **Prompt Sandwiching:** System prompt first, docs in body, restate query + schema at end.\n3. **Aggressive Pruning:** Restrict to top-5 chunks or use LLMLingua compression.""",

'promptbreeder.md': """# PromptBreeder (Fernando et al., Google DeepMind, 2023)\n\n**Citation:** arXiv:2309.16797\n\n## Core Concept\nEvolutionary algorithm that co-evolves task-prompts AND the mutation-prompts that modify them (self-referential self-improvement).\n\n## Evolutionary Units\n1. **Task-Prompt (P):** Guides LLM to solve target task.\n2. **Mutation-Prompt (M):** Meta-instruction specifying how to mutate P.\n3. **Thinking-Style:** Cognitive heuristic for reasoning patterns.\n\n## Mutation Operators\n1. **Direct Mutation:** Zero-shot mutation of P without M.\n2. **First-Order:** Applies M to P to yield improved P'.\n3. **Hyper-Mutation (Self-Referential):** Mutates the mutation prompts themselves.\n4. **Lamarckian Mutation:** Reverse-engineers prompts from correct solution traces.\n5. **EDA Shuffling:** Maintains diversity via semantic embeddings.\n\n## Results\nOutperforms CoT and Plan-and-Solve on GSM8K, SVAMP, hate speech detection.""",

'lats.md': """# Language Agent Tree Search (LATS) - Zhou et al. (2023)\n\n**Citation:** arXiv:2310.04406\n\n## Overview\nUnifies MCTS with LLMs for planning, acting, and reasoning without parameter updates.\n\n## Tri-Role LLM\n1. **Agent (Generator):** Proposes candidate actions/thoughts to expand tree branches.\n2. **Value Function (Evaluator):** Scores intermediate states via self-evaluative prompting.\n3. **Reflector (Optimizer):** Synthesizes verbal self-reflections on trajectory failure.\n\n## MCTS Adaptation\n1. **Selection:** UCT balances exploration vs. exploitation of high-reward trajectories.\n2. **Expansion:** Samples k diverse actions/thoughts at chosen node.\n3. **Evaluation:** Environment rewards + LLM semantic scoring.\n4. **Backpropagation:** Propagates values/visit counts; caches verbal reflections.\n\n## Results\n- HumanEval: 94.4% pass@1 with GPT-4 (state-of-the-art)\n- Also SOTA on WebShop and HotPotQA.""",
}

written = 0
for fname, content in files.items():
    path = os.path.join(base, fname)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    written += 1

print(f'Successfully wrote {written} snippet files.')
